### ISSUE TITLE
PentahoSystem.ERROR_0014

### ISSUE THREAD

**Issue by rodrigoGA** [ca0abinary/docker-pentaho#13]
I created the following docker compose:

```
version: "3"
services:
  # Pentaho BI
  pentaho:
    container_name: pentaho
    image: ca0abinary/docker-pentaho
    depends_on:
      - pentaho-pg
    ports:
      - "8080:8080"
    environment:
      - PGHOST=pentaho-pg
      - PGUSER=pentaho
      - PGPASSWORD=password
    volumes:
      - pentaho-hsqldb-data:/opt/pentaho/server/pentaho-server/data/hsqldb
      - pentaho-jackrabbit-data:/opt/pentaho/server/pentaho-server/pentaho-solutions/system/jackrabbit/repository
    networks:
      - integracion

  # PostgreSQL Database for Pentaho BI
  pentaho-pg:
    container_name: pentaho-pg
    image: postgres:9.4
    ports:
      - "4432:5432"
    environment:
      - POSTGRES_USER=pentaho
      - POSTGRES_PASSWORD=password
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - pentaho-pg-data:/var/lib/postgresql/data/pgdata
    networks:
      - integracion

volumes:
    pentaho-hsqldb-data: null
    pentaho-jackrabbit-data: null
    pentaho-pg-data: null
networks:
    integracion:
        driver: bridge
        ipam:
            driver: default
            config:
              - subnet: 172.19.0.0/16
```

then execute `docker-compose up`

and te output is:

```
pentaho       | 21:38:11,794 ERROR [Logger] Error: Pentaho
pentaho       | 21:38:11,795 ERROR [Logger] misc-org.pentaho.platform.engine.core.system.PentahoSystem: org.pentaho.platform.api.engine.PentahoSystemException: PentahoSystem.ERROR_0014 - Error while trying to execute startup sequence for org.pentaho.platform.engine.services.connection.datasource.dbcp.DynamicallyPooledDatasourceSystemListener
pentaho       | org.pentaho.platform.api.engine.PentahoSystemException: org.pentaho.platform.api.engine.PentahoSystemException: PentahoSystem.ERROR_0014 - Error while trying to execute startup sequence for org.pentaho.platform.engine.services.connection.datasource.dbcp.DynamicallyPooledDatasourceSystemListener
pentaho       | 	at org.pentaho.platform.engine.core.system.PentahoSystem.notifySystemListenersOfStartup(PentahoSystem.java:369)
pentaho       | 	at org.pentaho.platform.engine.core.system.PentahoSystem.init(PentahoSystem.java:331)
pentaho       | 	at org.pentaho.platform.engine.core.system.PentahoSystem.init(PentahoSystem.java:227)
pentaho       | 	at org.pentaho.platform.web.http.context.SolutionContextListener.contextInitialized(SolutionContextListener.java:162)
pentaho       | 	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4853)
pentaho       | 	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5314)
pentaho       | 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
pentaho       | 	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:725)
pentaho       | 	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701)
pentaho       | 	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717)
pentaho       | 	at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1092)
pentaho       | 	at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1834)
pentaho       | 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
pentaho       | 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
pentaho       | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
pentaho       | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
pentaho       | 	at java.lang.Thread.run(Thread.java:745)
pentaho       | Caused by: org.pentaho.platform.api.engine.PentahoSystemException: PentahoSystem.ERROR_0014 - Error while trying to execute startup sequence for org.pentaho.platform.engine.services.connection.datasource.dbcp.DynamicallyPooledDatasourceSystemListener
pentaho       | 	at org.pentaho.platform.engine.core.system.PentahoSystem$2.call(PentahoSystem.java:451)
pentaho       | 	at org.pentaho.platform.engine.core.system.PentahoSystem$2.call(PentahoSystem.java:433)
pentaho       | 	at org.pentaho.platform.engine.core.system.PentahoSystem.runAsSystem(PentahoSystem.java:412)
pentaho       | 	at org.pentaho.platform.engine.core.system.PentahoSystem.notifySystemListenersOfStartup(PentahoSystem.java:433)
pentaho       | 	at org.pentaho.platform.engine.core.system.PentahoSystem.access$000(PentahoSystem.java:83)
pentaho       | 	at org.pentaho.platform.engine.core.system.PentahoSystem$1.call(PentahoSystem.java:364)
pentaho       | 	at org.pentaho.platform.engine.core.system.PentahoSystem$1.call(PentahoSystem.java:361)
pentaho       | 	at org.pentaho.platform.engine.core.system.PentahoSystem.runAsSystem(PentahoSystem.java:412)
pentaho       | 	at org.pentaho.platform.engine.core.system.PentahoSystem.notifySystemListenersOfStartup(PentahoSystem.java:361)
pentaho       | 	... 16 more
pentaho       | Caused by: java.lang.NullPointerException
pentaho       | 	at org.pentaho.platform.repository.JcrBackedDatasourceMgmtService.init(JcrBackedDatasourceMgmtService.java:67)
pentaho       | 	at org.pentaho.platform.engine.core.system.objfac.AbstractSpringPentahoObjectFactory.retreiveObject(AbstractSpringPentahoObjectFactory.java:266)
pentaho       | 	at org.pentaho.platform.engine.core.system.objfac.AbstractSpringPentahoObjectFactory.get(AbstractSpringPentahoObjectFactory.java:82)
pentaho       | 	at org.pentaho.platform.engine.core.system.objfac.AggregateObjectFactory.get(AggregateObjectFactory.java:273)
pentaho       | 	at org.pentaho.platform.engine.core.system.objfac.AggregateObjectFactory.get(AggregateObjectFactory.java:137)
pentaho       | 	at org.pentaho.platform.engine.services.connection.datasource.dbcp.NonPooledDatasourceSystemListener.getListOfDatabaseConnections(NonPooledDatasourceSystemListener.java:137)
pentaho       | 	at org.pentaho.platform.engine.services.connection.datasource.dbcp.NonPooledDatasourceSystemListener.startup(NonPooledDatasourceSystemListener.java:53)
pentaho       | 	at org.pentaho.platform.engine.core.system.PentahoSystem$2.call(PentahoSystem.java:442)
pentaho       | 	... 24 more

```
